comment_width = 60
condense_wildcard_suffixes = true
fn_single_line = true
match_block_trailing_comma = true
# max_width = 80
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
report_todo = "unnumbered"
report_fixme = "unnumbered"
struct_field_align_threshold = 20
tab_spaces = 4
trailing_comma = "always"
wrap_comments = true
match_arm_blocks = false
blank_lines_lower_bound = 0
